### ISSUE TITLE
Not able to save in IE and Edge

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpa-apgf#147]
In IE and Edge, the save file dialog windows doesn't close and the file is not saved. Check if ou npm module file-saver support IE 11 and Edge

**Comment by bchagnon** [comment]
Console error message in Edge:
```
TypeError: Function expected
   at save (https://s-bsc-geoappint.nrn.nrcan.gc.ca/fgpa/fgpa-latest/av-main.js:151490:13)
   at fn (Function code:2:160)
   at callback (https://s-bsc-geoappint.nrn.nrcan.gc.ca/fgpa/fgpa-latest/av-main.js:56536:17)
   at Scope.prototype.$eval (https://s-bsc-geoappint.nrn.nrcan.gc.ca/fgpa/fgpa-latest/av-main.js:47618:9)
   at Scope.prototype.$apply (https://s-bsc-geoappint.nrn.nrcan.gc.ca/fgpa/fgpa-latest/av-main.js:47718:13)
   at Anonymous function (https://s-bsc-geoappint.nrn.nrcan.gc.ca/fgpa/fgpa-latest/av-main.js:56541:17)
   at jQuery.event.dispatch (https://s-bsc-geoappint.nrn.nrcan.gc.ca/fgpa/fgpa-latest/av-main.js:4815:6)
   at elemData.handle (https://s-bsc-geoappint.nrn.nrcan.gc.ca/fgpa/fgpa-latest/av-main.js:4627:5)
```

Console error message in IE 11:
```
TypeError: Object doesn't support this action
   at save (https://s-bsc-geoappint.nrn.nrcan.gc.ca/fgpa/fgpa-latest/av-main.js:151490:13)
   at fn (Function code:2:160)
   at callback (https://s-bsc-geoappint.nrn.nrcan.gc.ca/fgpa/fgpa-latest/av-main.js:56536:17)
   at Scope.prototype.$eval (https://s-bsc-geoappint.nrn.nrcan.gc.ca/fgpa/fgpa-latest/av-main.js:47618:9)
   at Scope.prototype.$apply (https://s-bsc-geoappint.nrn.nrcan.gc.ca/fgpa/fgpa-latest/av-main.js:47718:13)
   at Anonymous function (https://s-bsc-geoappint.nrn.nrcan.gc.ca/fgpa/fgpa-latest/av-main.js:56541:17)
   at jQuery.event.dispatch (https://s-bsc-geoappint.nrn.nrcan.gc.ca/fgpa/fgpa-latest/av-main.js:4815:6)
   at elemData.handle (https://s-bsc-geoappint.nrn.nrcan.gc.ca/fgpa/fgpa-latest/av-main.js:4627:5)
```
